### ISSUE TITLE
ERROR: CANNOT FIND ENTRY FILE INDEX.IOS.JS IN ANY OF THE ROOTS!

### ISSUE THREAD

**Issue by Pfurr** [edwinbosire/ASOS#1]

**Comment by hoscarcito** [comment]
you mean this one?
https://github.com/edwinbosire/ASOS/blob/master/index.ios.js

**Comment by Pfurr** [comment]
@hoscarcito no bro, when i open ios simulator it return this issue: ERROR: CANNOT FIND ENTRY FILE INDEX.IOS.JS IN ANY OF THE ROOTS! and it don't jobs, obviously

**Comment by edwinbosire** [comment]
Hi @pherm i've just cloned the project on a new computer and i've been able to run it successfully.
Maybe your problem is related to [this](https://github.com/facebook/react-native/issues/14246)
Also check if the node server is running in the terminal.

Best of luck.

**Comment by PrimeTimeTran** [comment]
I got this problem as well, I followed the previous suggestions of running.
`npm start -- --reset-cache`. After a few minutes it looked like it hung so I forced a stop with `ctrl+c`. Afterwards I closed all sessions of my command line prompt, restarted and navigated to my  projects root path and then ran `react-native run-ios`. I hope this helps.
